### ISSUE TITLE
Setting password on first launch doesn't work

### ISSUE THREAD

**Issue by qwertyasdef** [96jonesa/AutoBought#39]
I'm peer reviewing this and I can't get past password prompt.

The bug report section of the readme doesn't say what to include and I have no idea how your app works so here's all the information I can think of that might be relevant.

OS: Windows 10
Terminal: Powershell
Default browser (in case electron somehow cares about that): Firefox
Not sure if this matters since the repository includes its own jdk.
JAVA_HOME: points to jdk 11

What I did:
1. I cloned this repository from the main branch.
2. I extracted AutoBoughtPackageWindows.tar.gz.
3. I ran the setup file by double clicking.
4. I ran the start file by double clicking, and it didn't seem to work. The console window disappeared after so I'm not sure what happened.
5. I then opened Powershell and ran the start file from there, and it worked.
6. The electron app opened in a new window with a prompt for a password.
7. I entered "mypass" in the text box and hit enter, and nothing happened.
8. I tried clicking the submit button, which also didn't work.

What I expected:
After typing in the password and hitting enter or clicking submit, it should save my password and the prompt should go away so I can access the rest of the app.

Command line output:
```
Waiting for 57 seconds, press a key to continue ...
yarn run v1.22.10
$ concurrently -k "cross-env BROWSER=none yarn start" "yarn electron:start"
$ wait-on tcp:3000 && electron .
$ node react-scripts/scripts/start.js
[0] i ｢wds｣: Project is running at http://0.0.0.0:3000/
[0] i ｢wds｣: webpack output is served from
[0] i ｢wds｣: Content not from webpack is served from C:\Users\Brian\Documents\U Washington\2 Sophomore\3 Spring\CSE 403\AutoBought\AutoBoughtPackage\electron-react\public
[0] i ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0]
[1]
[0] Compiled with warnings.
[0]
[0] src\App.js
[0]   Line 24:8:  React Hook useEffect has missing dependencies: 'fetchCheckAndPurchase', 'fetchLoginData', and 'fetchPaymentData'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
[0]
[0] Search for the keywords to learn more about each warning.
[0] To ignore, add // eslint-disable-next-line to the line before.
[0]

```

Screenshot of app:
![image](https://user-images.githubusercontent.com/10069786/119598152-40372800-bd97-11eb-8871-6e943bd3963d.png)

**Comment by qwertyasdef** [comment]
Update:
If I build the app and run that, double clicking the start file works fine. When entering the password, it still doesn't work but this time I get a red error popup.
![image](https://user-images.githubusercontent.com/10069786/119600111-34e5fb80-bd9b-11eb-9b48-5cbc31b626f1.png)

**Comment by 96jonesa** [comment]
@qwertyasdef The red error popup you got in the image occurs because the backend wasn't given enough time to start before the frontend started - did you wait the 60second the command line says to wait (good), or did you press a key to continue (bad)?

The screenshot of the command line output seems to show that you pressed a key to continue after 3 seconds (there is still a 57 second wait there), so that may be caused by the same issue.

As for windows_start.bat working when called in powershell but not when executed in file explorer - the execution should be the same regardless. Did you perhaps accidentally double click the windows_start.bat in the scripts directory instead of the one in the AutoBoughtPackage directory?

**Comment by qwertyasdef** [comment]
I guess I did something wrong with the windows_start.bat the first time. I tried again and double clicking works fine now.

I tried waiting for 60 seconds, but I get the same error. I though maybe it needed longer since I'm running on a laptop, but I changed the delay to 300 seconds and it still doesn't work.

**Comment by 96jonesa** [comment]
@maryamsaleh @bduong2 have you seen this red error box / do you know what causes it?

**Comment by maryamsaleh** [comment]
> @maryamsaleh @bduong2 have you seen this red error box / do you know what causes it (assuming the backend is running before the frontend starts)?

Yes, this error pops up whenever an HTTP request to the backend fails. The way we're throwing the error in `App.js` looks something like this:
`fetch("the URL that verifies the password").catch(alertConnectionError)`, where `alertConnectionError` displays the red error box that @qwertyasdef is seeing. 
So, if the error appears, it means that `fetch()` failed (which I've only ever seen happen due to the frontend not being able to connect to the backend). I assume this means that something caused the backend to not start up correctly, but it's definitely possible that something else caused `fetch()` to throw an error.

@96jonesa do you know if there's any way to view console output from the backend if you start it by double-clicking the .bat file? Checking for errors/warnings thrown by the backend and also checking for errors in the frontend dev console is probably the best way to debug this.
